image: node:8.10

pipelines:
  default:
    - step:
        caches:
          - node
        script:
          - npm install
          - npm test
  branches:
    master:
      - step:
          script:
            - npm install
            #- npm run test
            - npm run build
          artifacts:
            - build/**
      - step:
          image: atlassian/pipelines-awscli
          deployment: production
          script:
            - aws s3 sync --delete build s3://$AWS_PROD_BUCKET_TARGET
