image: node:8.10

pipelines:
  default:
    - step:
        caches:
          - node
        script:
          - npm install
          - npm test
  branches:
    master:
      - step:
          script:
            - npm install
            #- npm run test
            - npm run build
          artifacts:
            - build/**
      - step:
          deployment: production
          script:
            - pipe: atlassian/aws-s3-deploy:0.2.1
              variables:
                 AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                 AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                 AWS_DEFAULT_REGION: "us-east-2"
                 S3_BUCKET: $AWS_PROD_BUCKET_TARGET
                 LOCAL_PATH: "build"
                 ACL: "public-read"